### PR TITLE
Add views for: post list, post details and post filter

### PR DESCRIPTION
**Pull request by zeraye**
Add views for:

- post list
- post details
- post filter

@majewska-mi if you want to open and test locally (on your phone) message me. I will help you set up everyting, it's really easy.

I don't expect you to check the quality of the code in terms of typescript or react. I care more about UI/UX, i.e. comments on the design, text placement and button names.

Test coverage is currently not satisfactory, if the design is approved, in the very next update I will add more tests.

I apologize for the size of this pull request. In the future I will make sure that pull requests are definitely smaller and cover preferably one view.

Video with preview:

https://github.com/MiNISpaceMobile/minispace-mobile/assets/53649257/d390b354-5b8e-423c-b7cb-105b1cb38d78

### CODE REVIEW

**Comment by zeraye** [comment]
@majewska-mi thank you for your feedback (via messenger). I couldn't add separate count for every reaction that doensn't feel cramped. 

@WildJellybear pointed out that the post filters basically match events. Instead, the post filters should only include whether you want to see posts from your friend's events. So I moved posts filters to events view and added new filters (just chips) for posts. Also participants list and join/leave buttons shouldn't be in post details. These components are moved to event details.

Overall:
- add return button
- remove participats list
- remove join/leave buttons
- move filters to event list
- add simple filters (chips)
- add report functionality
- restyled reactions (make them closer to each other)

You can see changes here:

https://github.com/MiNISpaceMobile/minispace-mobile/assets/53649257/e1641a9b-ad77-4657-b27e-4b7b44bcda33

**Comment by michalina-majewska** [comment]
Are you sure that a separate counter for each reaction is impossible? I'd try adding it below every reaction. Your way looks really well but we are losing on UX - a user doesn't know wether the reactions were positive or negative.

**Comment by majewska-mi** [comment]
Are you sure that a separate counter for each reaction is impossible? I'd try adding it below every reaction. Your way looks really well but we are losing on UX - a user doesn't know wether the reactions were positive or negative.

**Comment by majewska-mi** [comment]
For me, it's not clear that 'wydarzenia znajomych' isn't a title for what I'm seeing now. Maybe add a 'Filtry: '? (just a suggestion, you can think of something else to address this issue)

image

**Comment by majewska-mi** [comment]
I really like the report box. (I'd only change 'sprzeczny jest' to 'jest sprzeczny') Generally, good job, I don't see any more problems

**Comment by zeraye** [comment]
I added filter label and fix spelling in report dialog

Screenshot_2024-05-17-12-04-32-878_host exp exponent

**Review by majewska-mi — APPROVED** [review]

**Pull request merged**
