### PR TITLE
Add event list with filters

### PR DESCRIPTION
**Pull request by zeraye**
I added event list with filters (formerly post filters). Past event have more purple color and rating (you can rate event that you have attended). Current/future events have tag for low available space and no available space. I also make checkbox leading (left of the text) instead of trailing.

https://github.com/MiNISpaceMobile/minispace-mobile/assets/53649257/16c2dd12-46aa-472b-adad-70f6d81dc0cc

### CODE REVIEW

**Comment by majewska-mi** [comment]
After another discussion with @Patonymous I suggest you try changing colors in active filters to the colors in the picture: 
IMG_3529.

**Comment by majewska-mi** [comment]
Also, separate previous events and current/upcoming events with a line and a label.

**Comment by zeraye** [comment]
> After another discussion with @Patonymous I suggest you try changing colors in active filters to the colors in the picture: IMG_3529.

442503077_783662330408330_6855745917175591695_n

**Comment by zeraye** [comment]
> Also, separate previous events and current/upcoming events with a line and a label.

F_d880ML

**Comment by zeraye** [comment]
@majewska-mi I added divider for first inactive event and select icon for segmented buttons in event filters

**Review by majewska-mi — APPROVED** [review]

**Pull request merged**
